=== shefalibhute/JEE/Reference Demos/XMLParser/src/Employee.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="employee-details">
<xs:complexType>
<xs:sequence>
	<xs:element name="emp" minOccurs="1" maxOccurs="unbounded">
	<xs:complexType>
	<xs:attribute name="id" type="xs:integer" use="required"/>
	<xs:sequence>
		<xs:element name="name" maxOccurs="1">
		<xs:complexType>
		<xs:sequence>
			<xs:element name="first-name" type="xs:string"/>
			<xs:element name="last-name" type="xs:string"/>
		</xs:sequence>
		</xs:complexType>
		</xs:element>
		<xs:element name="depart">
		<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:enumeration value="D001"/>
			<xs:enumeration value="D002"/>
			<xs:enumeration value="D003"/>
			<xs:enumeration value="D004"/>
		</xs:restriction>
		</xs:simpleType>
		</xs:element>
		<xs:element name="salary">
		<xs:simpleType>
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="2000"/>
			<xs:maxInclusive value="2000000"/>
		</xs:restriction>
		</xs:simpleType>
		</xs:element>
		<xs:element name="phone">
		<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:minLength value="12"/>
			<xs:maxLength value="16"/>
		</xs:restriction>
		</xs:simpleType>
		</xs:element>
		<xs:element name="address" maxOccurs="1">
		<xs:complexType>
		<xs:sequence>
			<xs:element name="resi" type="xs:string"/>
			<xs:element name="off" type="xs:string"/>
		</xs:sequence>
		</xs:complexType>
		</xs:element>
	</xs:sequence>
	</xs:complexType>
	</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== shefalibhute/JEE/Reference Demos/XMLParser/Employee.xml
<?xml version="1.0" encoding="UTf-8"?>
<employee-details xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Employee.xsd">
	<emp id="1001">
	<name>
		<first-name>Tanmoy</first-name>
		<last-name>Hazra</last-name>
	</name>
	<depart>D001</depart>
	<salary>646200</salary>
	<phone>033-25435318</phone>
	<address>
		<resi>Shyambazar</resi>
		<off>SaltLake</off>
	</address>
	</emp>
	<emp id="1002">
	<name>
		<first-name>Avijit</first-name>
		<last-name>Sawant</last-name>
	</name>
	<depart>D004</depart>
	<salary>64600</salary>
	<phone>022-25435318</phone>
	<address>
		<off>Andheri</off>
		<resi>Khar</resi>
	</address>
	</emp>
</employee-details>
